---
- name: Hello World!
  hosts: all
 
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes

- name: Upgrade System
  apt: 
    update_cache: yes
    upgrade: yes

