---
- name: Upgrade!
  hosts: all
  



- name: Update APT package cache
  command: apt update_cache=yes

- name: Upgrade APT to the lastest packages
  command: apt upgrade=safe

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

