---
- name: Package updates
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: apt cache update
      apt: update_cache=yes
           cache_valid_time=3600

    - name: apt upgrade
      apt: upgrade=safe

